services:
  # The Database (postgreSql)
  db:
    image: docker.io/library/postgres:18.3
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/
    expose:
      - "5432"
    env_file:
      - ./backend/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Cache (redis)
  redis:
    image: docker.io/library/redis:8-alpine
    restart: always
    expose:
      - "6379"

  # The Backend (Django/Bolt)
  bolt:
    build:
      context: ./backend
      # dockerfile: Dockerfile.dev
    image: localhost/bdayateam/backend:latest
    env_file:
      - ./backend/.env
    volumes:
      - backend_media:/app/media_files
      - backend_static:/app/static_files
      - ./backend/backups:/app/backups
      # - ./backend:/app #! dev only
      - /app/.venv
      - /app/__pycache__
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/health/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - backups/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Huey Worker
  huey:
    image: localhost/bdayateam/backend:latest
    restart: always
    env_file:
      - ./backend/.env
    command: ["uv", "run", "--no-dev", "manage.py", "run_huey"]
    develop:
      watch:
        - action: sync+restart
          path: ./backend/core/tasks.py
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - backups/
        
        - action: sync+restart
          path: ./backend/notifications/tasks.py
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - backups/
        
        - action: sync+restart
          path: ./backend/organizer/tasks.py
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - backups/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # websocket (daphne)
  daphne:
    image: localhost/bdayateam/backend:latest
    restart: always
    env_file:
      - ./backend/.env
    command: ["uv", "run", "--no-dev", "daphne", "-b", "0.0.0.0", "-p", "8001", "BdayaTeam.asgi:application"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # The Frontend (Next.js)
  nextjs:
    build:
      context: ./frontend
      # dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_MEDIA_URL: ${NEXT_PUBLIC_MEDIA_URL}
        NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
        NEXT_PUBLIC_UNOPTIMIZED: ${NEXT_PUBLIC_UNOPTIMIZED}
        NEXT_API_URL: ${NEXT_API_URL}
    image: localhost/bdayateam/frontend:latest
    # image: bdayateam/frontend:dev
    env_file:
      - ./frontend/.env
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - nextjs_static:/app/.next/static
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/.env
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      bolt:
        condition: service_started

  # The Reverse Proxy (Nginx)
  nginx:
    image: docker.io/library/nginx:alpine
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx_main.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_teamBdaya_docker.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/localhost+1-key.pem:/etc/nginx/ssl/localhost+1-key.pem:ro
      - ./backend/localhost+1.pem:/etc/nginx/ssl/localhost+1.pem:ro
      - backend_static:/app/static_files:ro
      - backend_media:/app/media_files:ro
      - nextjs_static:/usr/share/nginx/nextjs_static:ro
    depends_on:
      bolt:
        condition: service_started
      nextjs:
        condition: service_started
  
volumes:
  db-data:
  nextjs_static:
  backend_media:
  backend_static:
