# Generated by Django 5.2.8 on 2025-11-28 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_member_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicals', to='core.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.track')),
            ],
            options={
                'ordering': ['-task_number', '-uploaded_at'],
                'unique_together': {('task_number', 'track')},
            },
        ),
    ]
