# Generated by Django 6.0.1 on 2026-04-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.track')),
            ],
            options={
                'ordering': ('task_number', '-track_id'),
                'unique_together': {('task_number', 'track')},
            },
        ),
    ]
