# Generated by Django 5.2.8 on 2025-11-27 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicals', to='core.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/None task <django.db.models.fields.PositiveIntegerField> %Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('degree', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.member')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.track')),
            ],
            options={
                'ordering': ['-task_number', '-uploaded_at'],
                'unique_together': {('task_number', 'member')},
            },
        ),
    ]
