# Generated by Django 5.2.8 on 2025-11-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_member_course'),
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_number', 'track')},
        ),
        migrations.RemoveField(
            model_name='task',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.RemoveField(
            model_name='task',
            name='signed',
        ),
    ]
