# Generated by Django 5.2.8 on 2025-12-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
