# Generated by Django 6.0.1 on 2026-01-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_number', '-track_id']},
        ),
    ]
