# Generated by Django 5.2.8 on 2025-12-04 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_alter_task_task_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_number', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
