# Generated by Django 6.0.1 on 2026-01-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('task_number', '-track_id')},
        ),
    ]
