# Generated by Django 6.0.1 on 2026-05-03 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_task_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, null=True),
        ),
    ]
