# Generated by Django 6.0.1 on 2026-05-03 15:17

import django.db.models.deletion
import imagekit.models.fields
import technical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_task_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=technical.models.task_images_url)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technical.task')),
            ],
        ),
    ]
