# Generated by Django 5.2.8 on 2025-12-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_alter_task_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technical',
        ),
    ]
