# Generated by Django 6.0.6 on 2026-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_remove_task_images_taskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='can_recive_tasks_after_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
