import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import LoadingProvider from "./loadingProvider";
import Header from "./components/header/header";
import AuthLoader from "./components/authLoader";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Team Bdaya",
  description: "Generated by create next app",
  icons: "/bdaya_black.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <LoadingProvider>
            <AuthLoader>
              <Header />
              <Toaster />
              {children}
            </AuthLoader>
          </LoadingProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
