import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import LoadingProvider from "./loadingProvider";
import Header from "./components/header/header";
import AuthLoader from "./components/authLoader";

export const metadata: Metadata = {
  title: "Team Bdaya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          <LoadingProvider>
            <AuthLoader>
              {children}
            </AuthLoader>
          </LoadingProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
