# Generated by Django 5.2.8 on 2025-11-28 15:53

import core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_member_course'),
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('code', models.CharField(blank=True, db_index=True, max_length=6, primary_key=True, serialize=False, unique=True, validators=[core.validators.validate_student_code])),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('collage_code', models.CharField(max_length=9, unique=True, validators=[core.validators.validate_collage_code])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='ReciviedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/None <django.db.models.fields.related.ForeignKey> %Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('degree', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.task')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
    ]
