# Generated by Django 6.0.1 on 2026-04-07 09:14

import core.validators
import django.db.models.deletion
import member.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('technical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('code', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True, validators=[core.validators.validate_member_code])),
                ('collage_code', models.CharField(max_length=9, unique=True, validators=[core.validators.validate_collage_code])),
                ('bonus', models.SmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning 1', 'Warning1'), ('warning 2', 'Warning2'), ('fired', 'Fired')], default='normal', max_length=10)),
                ('bdaya_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.track')),
            ],
            options={
                'ordering': ('-track', '-joined_at'),
            },
        ),
        migrations.CreateModel(
            name='ReciviedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('technical_notes', models.TextField(blank=True, null=True)),
                ('degree', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('recived_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_sent', to='member.member')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recivied', to='technical.task')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='ReciviedTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=member.models.task_upload_path)),
                ('file_name', models.CharField(max_length=100)),
                ('recivied_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='member.reciviedtask')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['track', 'joined_at'], name='member_memb_track_i_465cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reciviedtask',
            unique_together={('task', 'member')},
        ),
    ]
