# Generated by Django 5.2.8 on 2025-11-27 21:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True, validators=[core.validators.validate_student_code]),
        ),
    ]
