# Generated by Django 6.0.1 on 2026-04-25 19:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_pushsubscription'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTrackFileExtention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Allowed Extension (eg., png, py, cs, ....)')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ext', to='core.track')),
            ],
        ),
    ]
