# Generated by Django 5.2.8 on 2025-12-26 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_reciviedtask_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
