# Generated by Django 5.2.8 on 2025-12-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
