# Generated by Django 5.2.8 on 2025-12-04 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciviedtask',
            name='recived_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
