# Generated by Django 5.2.8 on 2025-12-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-track', '-joined_at')},
        ),
    ]
