# Generated by Django 5.2.8 on 2025-12-04 15:49

import django.db.models.deletion
import member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_reciviedtask_recived_at'),
        ('technical', '0004_delete_technical'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reciviedtask',
            unique_together={('task', 'member')},
        ),
        migrations.CreateModel(
            name='ReciviedTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=member.models.task_upload_path)),
                ('recivied_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='member.reciviedtask')),
            ],
        ),
        migrations.RemoveField(
            model_name='reciviedtask',
            name='file',
        ),
    ]
