# Generated by Django 5.2.8 on 2026-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('fired', 'Fired')], default='normal', max_length=10),
        ),
    ]
