# Generated by Django 6.0.1 on 2026-01-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_track_image'),
        ('member', '0005_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.track'),
        ),
    ]
