# Generated by Django 6.0.1 on 2026-01-27 09:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG', unique=True),
        ),
    ]
