# Generated by Django 6.0.1 on 2026-01-31 21:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True, validators=[core.validators.validate_member_code]),
        ),
    ]
