# Generated by Django 6.0.1 on 2026-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning 1', 'Warning1'), ('warning 2', 'Warning2'), ('fired', 'Fired')], default='normal', max_length=10),
        ),
    ]
