# Generated by Django 6.0.1 on 2026-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_description_track_en_description_and_more'),
        ('member', '0009_alter_member_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['track', 'joined_at'], name='member_memb_track_i_465cae_idx'),
        ),
    ]
