# Generated by Django 6.0.1 on 2026-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_member_memb_track_i_465cae_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciviedtask',
            name='technical_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
