# Generated by Django 6.0.1 on 2026-03-23 17:21

from django.db import migrations

def create_one_to_one_filed(app, schema_editor):
    member_obj = app.get_model("member", "Member")
    user_obj = app.get_model("core", "BdayaUser")
    
    for member in member_obj.objects.all():
        try:
            found_user = user_obj.objects.get(email=member.email)
            member.bdaya_user = found_user
            member.save()
        except:
            print(f"No User Found with email {member.email}")
    

class Migration(migrations.Migration):
    

    dependencies = [
        ('member', '0012_member_bdaya_user'),
    ]

    operations = [
        migrations.RunPython(create_one_to_one_filed)
    ]
