# Generated by Django 6.0.1 on 2026-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_remove_member_email_remove_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciviedtaskfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
