# Generated by Django 6.0.1 on 2026-03-25 15:29

from django.db import migrations
import os

def create_file_name(app, schema_editor) -> None:
    recivied_task_file = app.get_model("member", "ReciviedTaskFile")
    files = recivied_task_file.objects.all()
    for file in files:
        if file.file:
            file_name = os.path.basename(file.file.name)
            file.file_name = file_name
            file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_reciviedtaskfile_file_name'),
    ]

    operations = [
        migrations.RunPython(create_file_name)
    ]
