# Generated by Django 6.0.1 on 2026-03-25 15:39

import member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20260325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciviedtaskfile',
            name='file',
            field=models.FileField(upload_to=member.models.task_upload_path),
        ),
        migrations.AlterField(
            model_name='reciviedtaskfile',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
