# Generated by Django 6.0.1 on 2026-04-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_reciviedtask_signed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciviedtask',
            name='signed_by',
        ),
    ]
