# Generated by Django 6.0.1 on 2026-04-07 09:14

import django.contrib.postgres.fields
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_register_enabled', models.BooleanField(default=True)),
                ('organizer_can_edit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'Name'), ('status', 'Status'), ('track', 'Track'), ('bonus', 'Bonus'), ('email', 'Email'), ('phone', 'Phone')], max_length=30), blank=True, default=list)),
                ('site_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='public/site')),
                ('hero_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='public/hero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceAllowedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.track')),
            ],
            options={
                'ordering': ('track', 'day'),
                'unique_together': {('track', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=9)),
                ('excuse_reason', models.TextField(blank=True, null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='member.member')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_attendance', to='organizer.attendanceallowedday')),
            ],
            options={
                'unique_together': {('member', 'date')},
            },
        ),
    ]
