# Generated by Django 5.2.8 on 2025-12-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_reciviedtask_member'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAllowedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='old_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='new_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_attendance', to='organizer.attendanceallowedday'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'new_date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
