# Generated by Django 5.2.8 on 2025-12-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_reciviedtask_member'),
        ('organizer', '0002_attendanceallowedday_attendance_old_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='new_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='old_date',
        ),
    ]
