# Generated by Django 5.2.8 on 2025-12-25 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_track_description'),
        ('organizer', '0003_rename_new_date_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceallowedday',
            options={'ordering': ('track', 'day')},
        ),
        migrations.AddField(
            model_name='attendanceallowedday',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.track'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceallowedday',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceallowedday',
            unique_together={('track', 'day')},
        ),
    ]
