# Generated by Django 5.2.8 on 2025-12-31 01:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_register_enabled', models.BooleanField(default=True)),
                ('organizer_can_edit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('site_image', models.ImageField(blank=True, null=True, upload_to='site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
