# Generated by Django 5.2.8 on 2025-12-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_alter_sitesetting_organizer_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='organizer_can_edit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
