# Generated by Django 5.2.8 on 2025-12-31 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_sitesetting_organizer_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='organizer_can_edit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
