# Generated by Django 5.2.8 on 2026-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_sitesetting_organizer_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/site'),
        ),
    ]
