# Generated by Django 6.0.1 on 2026-01-26 01:35

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_sitesetting_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='public/hero'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='public/site'),
        ),
    ]
