# Generated by Django 6.0.1 on 2026-04-05 23:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_sitesetting_hero_image_alter_sitesetting_site_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='organizer_can_edit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'Name'), ('status', 'Status'), ('track', 'Track'), ('bonus', 'Bonus'), ('email', 'Email'), ('phone', 'Phone')], max_length=30), blank=True, default=list),
        ),
    ]
