# Generated by Django 6.0.1 on 2026-04-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_attendance_by_alter_sitesetting_organizer_can_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='by',
        ),
    ]
