import "./globals.css";
import API from "../utils/api.server";
import Header from "../components/header";
import { getMessages } from 'next-intl/server';
import type { Metadata, Viewport } from "next";
import { Toaster } from "@/components/ui/sonner";
import AuthLoader from "../components/authLoader";
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { serverGraphQL } from "../utils/api_utils";
import { GET_IMAGES_SETTINGS } from "../utils/graphql_helpers";
import type { SettingsImagesQuery } from "../generated/graphql";
import { LoadingProvider, RegisterNextThemeProvider, RegisterThemeProvider } from "./clientProviders";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_API_URL || "https://localhost"),
  applicationName: "Team Bdaya",
  category: "Courses",
  creator: "NooR MaseR",
  publisher: "Team Bdaya",
  title: {
    default: "Team Bdaya",
    template: "%s - Team Bdaya"
  },
  description: "Generated by Team Bdaya",
  authors: [
    { name: "NooR MaseR" },
    { name: "Hythim" },
    { name: "Mohamed Zainhom" },
  ],
  alternates: {
    canonical: "https://localhost",
    languages: {
      en: "https://localhost/en",
      ar: "https://localhost/ar",
    }
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#292929' },
  ],
  maximumScale: 1,
};

export function generateStaticParams() {
  return [
    { locale: 'en' },
    { locale: 'ar' }
  ];
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;
  setRequestLocale(locale);

  const messages = await getMessages({ locale });
  const [authResponse, imagesResponse] = await Promise.allSettled([
    API.GET("/api/test-auth/"),
    serverGraphQL<SettingsImagesQuery>(GET_IMAGES_SETTINGS)
  ]);

  const authData = authResponse.status === "fulfilled" && authResponse.value.data ? authResponse.value.data : null;
  const imagesData = imagesResponse.status === "fulfilled" ? imagesResponse.value.data.allSettings : null;

  return (
    <html lang={locale} dir={locale === 'ar' ? "rtl" : 'ltr'} suppressHydrationWarning>
      <head>
        <link rel="shortcut icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="manifest" href={`/manifest.json?role=${authData?.role}&track=${authData?.track?.name}`} />
      </head>
      <body className="color-trans dark:bg-(--dark-color)">
        <LoadingProvider>
          <RegisterNextThemeProvider attribute='class' defaultTheme="system" enableSystem>
            <NextIntlClientProvider messages={messages}>
              <RegisterThemeProvider>
                <AuthLoader authData={authData} imagesData={imagesData}>
                  <Header />
                  <Toaster />
                  {children}
                </AuthLoader>
              </RegisterThemeProvider>
            </NextIntlClientProvider>
          </RegisterNextThemeProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
