import "./globals.css";
import Header from "../components/header";
import { getMessages } from 'next-intl/server';
import type { Metadata, Viewport } from "next";
import { Toaster } from "@/components/ui/sonner";
import AuthLoader from "../components/authLoader";
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { SerwistProvider } from "@serwist/turbopack/react";
import DynamicManifest from "../components/dynamic_manifest";
import ClickSparkWrapper from "../components/click_spark_wrapper";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { LoadingProvider, RegisterNextThemeProvider, RegisterThemeProvider } from "./clientProviders";
import { Suspense } from "react";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_API_URL || "https://localhost"),
  applicationName: "Team Bdaya",
  category: "Courses",
  creator: "NooR MaseR",
  publisher: "Team Bdaya",
  title: {
    default: "Team Bdaya",
    template: "%s - Team Bdaya"
  },
  description: "Generated by Team Bdaya",
  authors: [
    { name: "NooR MaseR" },
    { name: "Hythim" },
    { name: "Mohamed Zainhom" },
  ],
  alternates: {
    canonical: "https://localhost",
    languages: {
      en: "https://localhost/en",
      ar: "https://localhost/ar",
    }
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#292929' },
  ],
  maximumScale: 1,
};

export function generateStaticParams() {
  return [
    { locale: 'en' },
    { locale: 'ar' }
  ];
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;
  setRequestLocale(locale);

  const messages = await getMessages({ locale });

  return (
    <html lang={locale} dir={locale === 'ar' ? "rtl" : 'ltr'} suppressHydrationWarning>
      <head>
        <link rel="shortcut icon" href="/favicon.svg" type="image/svg+xml" />
        <DynamicManifest />
      </head>
      <body className="color-trans dark:bg-(--dark-color)">
        <SerwistProvider swUrl="/serwist/sw.js">
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <RegisterNextThemeProvider attribute='class' defaultTheme="system" enableSystem>
              <NextIntlClientProvider messages={messages}>
                <RegisterThemeProvider>
                  <ClickSparkWrapper>
                    <LoadingProvider>
                      <AuthLoader>
                        <Header />
                        <Toaster />
                        {children}
                      </AuthLoader>
                    </LoadingProvider>
                  </ClickSparkWrapper>
                </RegisterThemeProvider>
              </NextIntlClientProvider>
            </RegisterNextThemeProvider>
          </AppRouterCacheProvider>
        </SerwistProvider>
      </body>
    </html >
  );
}
