import "./globals.css";
import type { Metadata } from "next";
import Header from "../components/header";
import { getMessages } from 'next-intl/server';
import { Toaster } from "@/components/ui/sonner";
import AuthLoader from "../components/authLoader";
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { LoadingProvider, RegisterThemeProvider } from "./clientProviders";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_API_URL || "https://localhost"),
  applicationName: "Team Bdaya",
  category: "Courses",
  creator: "NooR MaseR",
  publisher: "Team Bdaya",
  title: "Team Bdaya",
  description: "Generated by Team Bdaya",
  authors: [
    { name: "NooR MaseR" },
    { name: "Hythim" },
    { name: "Mohamed Zainhom" },
  ],
  alternates: {
    canonical: "https://localhost",
    languages: {
      en: "https://localhost/en",
      ar: "https://localhost/ar",
    }
  },
};

export function generateStaticParams() {
  return [
    { locale: 'en' },
    { locale: 'ar' }
  ];
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} dir={locale === 'ar' ? "rtl" : 'ltr'}>
      <body>
        {/* <StoreProvider> */}
          <LoadingProvider>
            <NextIntlClientProvider messages={messages}>
              <AuthLoader>
                <RegisterThemeProvider>
                  <Header />
                  <Toaster />
                  {children}
                </RegisterThemeProvider>
              </AuthLoader>
            </NextIntlClientProvider>
          </LoadingProvider>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
