# Generated by Django 5.2.8 on 2025-11-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='course',
        ),
    ]
