# Generated by Django 5.2.8 on 2025-11-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_member_course'),
        ('member', '0001_initial'),
        ('technical', '0002_rename_notes_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='member.member'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
