# Generated by Django 6.0.1 on 2026-04-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
