# Generated by Django 5.2.8 on 2025-11-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_member_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdayauser',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.track'),
        ),
    ]
