# Generated by Django 5.2.8 on 2025-12-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_track_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='prefix',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
