# Generated by Django 6.0.1 on 2026-01-26 01:35

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_track_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='public/tracks'),
        ),
    ]
