# Generated by Django 6.0.1 on 2026-01-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_track_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
    ]
