# Generated by Django 6.0.1 on 2026-02-20 23:02

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trackcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='public/tracks'),
        ),
    ]
