# Generated by Django 6.0.1 on 2026-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_track_description_alter_track_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='description',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track',
            new_name='name',
        ),
        migrations.AddField(
            model_name='track',
            name='ar_description',
            field=models.TextField(default='اهتبار'),
            preserve_default=False,
        ),
    ]
