# Generated by Django 6.0.1 on 2026-03-23 17:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_description_track_en_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdayauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG', unique=True),
        ),
    ]
